### ISSUE TITLE
Fake Item effect does not work with an Entity ID

### ISSUE THREAD

**Issue by Dragoncraft000** [Ekpoa/PoaSkRewritev2#4]
Nothing happens if I try to use the fake item effect with an entitiy id.
No errors or stacktraces in the console or on skript reload.

Using the entity ID of a real entity does not work as well.

Example Code:
`spawn fake zombie at player for all players with id 50`
`fake 50 equipment slot "HAND" to dirt for all players`

PoaSK 4.1.1
Skript 2.8.5
Paper 1.20.4 (Build 496)

**Comment by Ekpoa** [comment]
should be fixed in latest version
